Feature: ReceiveOil_Create Api

Scenario: Test ReceiveOil Create
  Given url inventoryUrl
  Given path "/api/ReceiveOil/Create"
  Given request
  """
{
    "InvReceiveProdHd": {
        "BrnCode": "01L",
        "CompCode": "O",
        "CreatedBy": "10040371",
        "CreatedDate": null,
        "CurRate": 1,
        "Currency": "THB",
        "DeliveryNo": "",
        "DiscAmt": 0,
        "DiscAmtCur": 0,
        "DiscRate": "",
        "DocDate": "2022-01-21",
        "DocNo": "RO01L-2201####",
        "DocPattern": "RO01L-2201####",
        "DocStatus": "New",
        "DocType": "Oil",
        "DueDate": "2022-02-20",
        "EtaxAmt": 0,
        "EtaxAmtCur": 0,
        "Guid": "090d0902-685d-44a9-a509-23b943d42318",
        "InvAddrId": "",
        "InvAddress": "",
        "InvDate": "2023-07-14",
        "InvNo": "1234567890",
        "ItemCount": 0,
        "LocCode": "005",
        "NetAmt": 762.62,
        "NetAmtCur": 762.62,
        "PayAddrId": "",
        "PayAddress": "",
        "PoDate": "2022-01-20",
        "PoNo": "5400535353",
        "PoTypeId": "ZIN3",
        "Post": "N",
        "Remark": "",
        "RunNumber": 0,
        "ShippingAmt": 0,
        "ShippingAmtCur": 0,
        "Source": "",
        "SubAmt": 762.62,
        "SubAmtCur": 762.62,
        "SupCode": "01-พ210180",
        "SupName": "พีทึจีเอนเนอยี บมจ คลังลำปาง",
        "TaxBaseAmt": 712.7289719626168,
        "TaxBaseAmtCur": 712.7289719626168,
        "TotalAmt": 762.62,
        "TotalAmtCur": 762.62,
        "UpdatedBy": "10040371",
        "UpdatedDate": null,
        "VatAmt": 49.89102803738318,
        "VatAmtCur": 49.89102803738318,
        "VatRate": 0,
        "VatType": "VI"
    },
    "InvReceiveProdDts": [
        {
            "BrnCode": "01L",
            "CompCode": "O",
            "Density": 0,
            "DensityBase": 0,
            "DiscAmt": 0,
            "DiscAmtCur": 0,
            "DiscHdAmt": 0,
            "DiscHdAmtCur": 0,
            "DocNo": "RO01L-2201####",
            "DocType": "Oil",
            "IsFree": false,
            "ItemQty": 1,
            "ItemRemain": 0,
            "LocCode": "",
            "PdId": "08668",
            "PdName": "แม็คนิตรอน เซมิซินเธติก 15000 10w40   1ลิตร",
            "PoQty": 1,
            "ReturnQty": 0,
            "ReturnStock": 0,
            "SeqNo": 10,
            "StockQty": 1,
            "StockRemain": 0,
            "SubAmt": 0,
            "SubAmtCur": 0,
            "SumItemAmt": 144.86,
            "SumItemAmtCur": 144.86,
            "TaxBaseAmt": 0,
            "TaxBaseAmtCur": 0,
            "Temperature": 0,
            "TotalAmt": 0,
            "TotalAmtCur": 0,
            "UnitBarcode": "08668",
            "UnitId": "010",
            "UnitName": "ขวด",
            "UnitPrice": 144.86,
            "UnitPriceCur": 144.86,
            "VatAmt": 0,
            "VatAmtCur": 0,
            "VatRate": 0,
            "VatType": "",
            "WeightPrice": 0,
            "WeightQty": 0
        },
        {
            "BrnCode": "01L",
            "CompCode": "O",
            "Density": 0,
            "DensityBase": 0,
            "DiscAmt": 0,
            "DiscAmtCur": 0,
            "DiscHdAmt": 0,
            "DiscHdAmtCur": 0,
            "DocNo": "RO01L-2201####",
            "DocType": "Oil",
            "IsFree": false,
            "ItemQty": 1,
            "ItemRemain": 0,
            "LocCode": "",
            "PdId": "08674",
            "PdName": "แม็คนิตรอน 5000 20w50   4ลิตร",
            "PoQty": 1,
            "ReturnQty": 0,
            "ReturnStock": 0,
            "SeqNo": 20,
            "StockQty": 1,
            "StockRemain": 0,
            "SubAmt": 0,
            "SubAmtCur": 0,
            "SumItemAmt": 415.89,
            "SumItemAmtCur": 415.89,
            "TaxBaseAmt": 0,
            "TaxBaseAmtCur": 0,
            "Temperature": 0,
            "TotalAmt": 0,
            "TotalAmtCur": 0,
            "UnitBarcode": "08674",
            "UnitId": "002",
            "UnitName": "แกลลอน",
            "UnitPrice": 415.89,
            "UnitPriceCur": 415.89,
            "VatAmt": 0,
            "VatAmtCur": 0,
            "VatRate": 0,
            "VatType": "",
            "WeightPrice": 0,
            "WeightQty": 0
        },
        {
            "BrnCode": "01L",
            "CompCode": "O",
            "Density": 0,
            "DensityBase": 0,
            "DiscAmt": 0,
            "DiscAmtCur": 0,
            "DiscHdAmt": 0,
            "DiscHdAmtCur": 0,
            "DocNo": "RO01L-2201####",
            "DocType": "Oil",
            "IsFree": false,
            "ItemQty": 3,
            "ItemRemain": 0,
            "LocCode": "",
            "PdId": "08622",
            "PdName": "แม็คนิตรอน 2 ที ออโตลูบ  0.5 ลิตร",
            "PoQty": 3,
            "ReturnQty": 0,
            "ReturnStock": 0,
            "SeqNo": 30,
            "StockQty": 3,
            "StockRemain": 0,
            "SubAmt": 0,
            "SubAmtCur": 0,
            "SumItemAmt": 201.87,
            "SumItemAmtCur": 201.87,
            "TaxBaseAmt": 0,
            "TaxBaseAmtCur": 0,
            "Temperature": 0,
            "TotalAmt": 0,
            "TotalAmtCur": 0,
            "UnitBarcode": "08622",
            "UnitId": "010",
            "UnitName": "ขวด",
            "UnitPrice": 67.29,
            "UnitPriceCur": 67.29,
            "VatAmt": 0,
            "VatAmtCur": 0,
            "VatRate": 0,
            "VatType": "",
            "WeightPrice": 0,
            "WeightQty": 0
        }
    ]
}

  """
  When method POST
  Then status 200
  Then print response

@ignore @report=false
Scenario: Test ignore
  Given url "http://abc.xyz"
  Given path "demo"
  When method GET
  Then status 404